### ISSUE TITLE
how were the curated similarity cut-offs calculated?

### ISSUE THREAD

**Issue by xiestcn** [arpcard/rgi#101]
I found that every protein model in CARD has a **curated similarity cut-off** for determining AMR genes, my question is how was this **cut-off** calculated? is these a method we can calculate that ourselves?

**Comment by huynhw1** [comment]
Hey there @xiestcn!

The curated similarity cut-off are bit-scores that are calculated from BLAST alignments. We calculate the bit-scores by blasting the sequence either against CARD or NCBI. The bit-score that we get is assuming a perfect match. We set the bit-score just under this perfect value so that RGI can detect both perfect matches and strict matches. You can calculate the bit-score yourself using BLAST.

Thanks for asking, I hope I was able to answer your question.

------

William Huynh, CARD Curator-Developer

**Comment by xiestcn** [comment]
> Hey there @xiestcn!
> 
> The curated similarity cut-off are bit-scores that are calculated from BLAST alignments. We calculate the bit-scores by blasting the sequence either against CARD or NCBI. The bit-score that we get is assuming a perfect match. We set the bit-score just under this perfect value so that RGI can detect both perfect matches and strict matches. You can calculate the bit-score yourself using BLAST.
> 
> Thanks for asking, I hope I was able to answer your question.
> 
> William Huynh, CARD Curator-Developer

Thanks for your reply!!!
I'm still a little confused. You said **"set bit-score just under this perfect value"**, what's the rule/formula for setting the bit-score. For instance, for protein **CblA-1(model_id: 2)**, it's pass_bit_score in CARD is 575. and the self-BLAST bit_score is 616, how is the **pass_bit-score** set? I could not find the pattern when I inspected relationship between pass_bit_score and self-BLAST bit_score.

**Comment by huynhw1** [comment]
Hey @xiestcn !

The bit-score input are estimates based on a self-blast and other most similar models.

Thank you.

-------
William Huynh, CARD Curator-Developer
