### ISSUE TITLE
how can i get the Related Literature about AMR and Mutation for rgi result

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#106]
hi @arpcard ：
     when i get AMR result from RGI Main，i  wan to read Related Literature about AMR/mutation,
     what shoud i do?
thank

**Comment by arpcard** [comment]
Hello @feihongloveworld ,

The data produced by RGI main provides an ARO accession related to the AMR/mutation.
Using this, you can use your browser to browse the related ARO.
Try using:
https://card.mcmaster.ca/ontology/<ARO_HERE>

Where <ARO_HERE> is replaced with the ARO accession.

On this page, you can find the PMID attached to the AMR gene which you can read.

Thank you.

**Comment by feihongloveworld** [comment]
Thank you very much.

**Comment by feihongloveworld** [comment]
hi @arpcard 
      I found most of the literature the way you did。But there are some genes(https://card.mcmaster.ca/ontology/37489)  that are not documented in the website，so what shoud i to do for this AROid？

**Comment by arpcard** [comment]
Hi @feihongloveworld ,

Notice that it is a beta-lactamase. Due to beta-lactamases not having a strict nomenclature, and most are direct NCBI submissions, a lot of beta-lactamases do not have an associated paper. We at the CARD curation team have made the decision to include beta-lactamase genes regardless of whether there is a publication or not.

Thank you.

**Comment by feihongloveworld** [comment]
Thank you for your reply.
