### ISSUE TITLE
Can RGI run with paired end sequences

### ISSUE THREAD

**Issue by Vaishn17** [arpcard/rgi#12]

**Comment by arpcard** [comment]
Hello, while the latest version of RGI (4.0.2) supports Prodigal gene calling for low quality assemblies, short contigs, or merged metagenomic reads, it does not have support for raw FASTQ data (paired or otherwise). If you merge the paired sequences into consensus as a FASTA file, that will work. You'll need to use the command line version for this analysis, as the website has a file size limit.

**Comment by arpcard** [comment]
@Vaishn17 did this work for you?
