### ISSUE TITLE
rgi result can not be visualize

### ISSUE THREAD

**Issue by JALEM1** [arpcard/rgi#128]
Hello,

I ran rgi and got the output_file.json. then I used the parser command and parse this file into several json files.
[Result.zip](https://github.com/arpcard/rgi/files/5494957/Result.zip)

but they can not be visualized on the card website. I have attached all json files as a zip file by this request and it will be appreciated if you have a look at them. actually, it's more than 10 days that I am struggling with this issue.

thank you

**Comment by arpcard** [comment]
Hello,

I took a look at your jsons, you can visualize the output_file.json directly on the CARD website. However, the reason why the separate jsons aren’t visualizing is because they are empty.

If you take a look, you will notice that they are only 1KB in size and when opened, they contain no information. I suggest reading the documentation on the parser command to ensure that you split the json correctly. Otherwise, you would be fine just visualizing the output_file.json directly.

Thank you.


William Huynh, CARD Curator-Developer
David Braley Centre for Antibiotic Discovery
M.G. DeGroote Institute for Infectious Disease Research
McMaster University, Hamilton, Ontario L8S 4K1, Canada

**Comment by JALEM1** [comment]
Hello
thank you for your consideration.actually I cant visualize the output_file.json because I got this error the size of the file is more than 20 M. I have attached my jason file here. I parse this file to be visualized, with the below command.

rgi parser --input /path/to/output_file.Json --output /path/to/
[Json.file.zip](https://github.com/arpcard/rgi/files/5495408/Json.file.zip)

thank you
