### ISSUE TITLE
Question: technical definition of perfect, strict, and loose

### ISSUE THREAD

**Issue by alimayy** [arpcard/rgi#140]
Hi there,

Thanks for developing RGI. 

Regarding the perfect, strict, and loose hits, [Jia et al. 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5210516/) mentions:
> The RGI currently supports two detection model types (Protein Homolog and Protein Variant) and analyzes sequences under three paradigms—Perfect, Strict, and Loose (a.k.a. Discovery). The Perfect algorithm is most often applied to clinical surveillance as it detects perfect matches to the curated reference sequences and mutations in CARD.

Could you provide a more technical definition of these terms? For instance for 'perfect', I understand from https://github.com/arpcard/rgi/issues/101 that the self-mapping bit-scores determine the 'perfect' hits. Could you provide more info on how 'strict' and 'loose' thresholds are chosen? 

Thanks in advance,
Ali

**Comment by parwa28** [comment]
Can you please tell me how exactly I can use one of the detection models?

**Comment by agmcarthur** [comment]
@alimayy these detection models are used by CARD's Resistance Gene Identifier software: https://github.com/arpcard/rgi (contains full documentation). There is an online portal at https://card.mcmaster.ca/analyze/rgi. Also described in CARD's latest publication: https://pubmed.ncbi.nlm.nih.gov/36263822/

**Comment by Sebdu132** [comment]
I'm re-activating this thread because I feel that this "strict" category is a bit misleading. It may actually capture proteins highly divergent to the reference. For instance in this example (may 2026), a bitscore of 750 is given for proteins with only 42% identity to the reference adeF :  

<img width="1485" height="666" alt="Image" src="https://github.com/user-attachments/assets/6cace266-a9ea-4121-ba27-e05b1375b0ad" />

At such genetic distance, it is hard to infer the same resistance properties. Since there is no threshold based on the similarity in RGI, the "strict" category may greatly over-estimate the number of ARGs if used in some applications without additional filters (i.e. screening of metagenomic assembled contigs/MAGs).
