### ISSUE TITLE
Is there a way to generate a tsv file with identity and coverage of AMR genes obtained

### ISSUE THREAD

**Issue by ddh8602** [arpcard/rgi#151]
Hi. I was wondering if there is a way to generate a single tsv file from a directory containing .json files that summarizes important information from each file like gene, contig, start, end, %coverage, %identity, etc.  I would like to build a customized heatmap from 168 samples in R for a publication, but I want to include identity and coverage. If there's no such function, I believe this would be a nice plugin. Thanks in advance. 

**_NOTE: This is not an issue. I don't know to change the label to question._**

**Comment by fmaguire** [comment]
https://github.com/pha4ge/hAMRonization lets you create combined AMR reports (even across tools) in a standardised format from RGI produced jsons or tsv (*.txt) outputs.

Otherwise, it isn't too hard to combine the tsv outputs from RGI and feed into whatever customised heatmap plotting method you want to use e.g:

```import pandas as pd
from pathlib import Path

combined_results = []

# will find any *.txt file in any folder underneath the current directory
for report in Path('.').rglob('*.txt'):
    result = pd.read_csv(report, sep='\t')
    # create a column containing the filename of each report
    result['sample'] = report.with_suffix('').name
    combined_results.append(result)

combined_results = pd.concat(combined_results)```
