### ISSUE TITLE
Can not use RGI command by .py script

### ISSUE THREAD

**Issue by EugeneAeolus** [arpcard/rgi#169]
**Describe the bug**

When I ran a .py script for batch rgi processing, it raised an error: 
![image](https://user-images.githubusercontent.com/92861259/138086938-1ec78166-3fd7-43f3-b762-f43db0789070.png)

I don't know whether I need to write a code to activate the virtual environment of RGI?

**Input**
The script is as follows:

import os
import rgi

dir = '/home/yj/Rgi.test'
list = os.listdir(dir)  # list
for i in range(0, len(list)):
    path = os.path.join(dir, list[i])
    file = os.path.join(list[i])
    # if os.path.isfile(path):
    #     print(path)
    #     print(file)
    if 'genome.fasta' in path:
        file_name=file.split('.')[0]
        # print(file_name)
        rgi main -i path -o file_name --input_type contig --local --include_loose --clean

**CARD Version**
3.1.4

**RGI version**
3.1.4

Thanks for your help.

**Comment by fmaguire** [comment]
Unfortunately, you can't just run shell commands in python. 

`python -c "ls"` will give you an error because `ls` isn't a python command.

To run things in python scripts as if you were running them on the shell you need to use a library like [subprocess](https://docs.python.org/3/library/subprocess.html):

`python -c "import subprocess; subprocess.run('ls')"`
