### ISSUE TITLE
Heatmap command error RGI 7.0.0

### ISSUE THREAD

**Issue by namnh7** [arpcard/rgi#211]
I tried the command **`rgi heatmap -h`** but it is an error:

rgi: error: argument command: invalid choice: 'heatmap' (choose from 'main', 'tab', 'parser', 'load', 'auto_load', 'clean', 'galaxy', 'database', 'bwt', 'tm', 'card_annotation', 'wildcard_annotation', 'baits_annotation', 'remove_duplicates', 'kmer_build', 'kmer_query')

Is **heatmap** command removed?

**Comment by fmaguire** [comment]
`heatmap` and other visualisation tools for RGI/CARD data are scheduled to be moved to a new tool (https://github.com/arpcard/rgi-viz) that hasn't been released yet.  This is part of a simplification of the RGI codebase that should result in more visualisation capacity and a faster/easier to install RGI.

We only really recommend using RGI's stable releases (i.e., from https://github.com/arpcard/rgi/releases/ instead of using the pre-release development code) but to prevent anyone else having the same issue I've reverted the master branch to the last release and moved pre-release code to a `dev` branch.

If you re-install from the repo/conda or the release page https://github.com/arpcard/rgi/releases/ you will be able to use `rgi heatmap` as normal.
